services:
  app:
    container_name: assinatura-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - STAGE=local
      - SERVERLESS_ACCESS_KEY=AKA6v9Odgu2JNPmXAZKD9xC6TCpLx1P87oiTAJno9lQkT
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_HOSTNAME=localstack
      - LOCALSTACK_HOST=localstack
      - EDGE_PORT=4566
      - USE_IN_MEMORY_DB=true
      - SIGNATURES_REPOSITORY_DRIVER=memory
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev

  ui:
    image: nginx:1.27-alpine
    container_name: assinatura-ui
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx.conf:ro

  localstack:
    image: localstack/localstack:latest
    container_name: assinatura-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,apigateway,dynamodb,sqs,s3,sns,iam,logs
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  terraform:
    image: hashicorp/terraform:1.9
    container_name: terraform-cli
    working_dir: /workspace/terraform  
    volumes:
      - ./:/workspace
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1

volumes:
  node_modules:
