service: digitalSignature-v2

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'local'}
  region: us-east-1

plugins:
  - serverless-offline

functions:
  checkSignStatus:
    handler: src/handlers/checkSignStatus.handler
    events:
      - http:
          path: signature/status/{requestIdOrShortId}
          method: get
          cors: true


custom:
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: 3000
    lambdaPort: 3002
    host: 0.0.0.0
